### ISSUE TITLE
81: arithmetic expression: expecting primary: "i--"

### ISSUE THREAD

**Issue by ghost** [psqli/pcmsh#2]
I get an error when I run:
`cat /dev/urandom | ./pcm.sh > /dev/snd/pcmC0D3p`
The error is:

> ./pcm.sh: 81: arithmetic expression: expecting primary: "i--"

**Comment by psqli** [comment]
Thank you for reporting this.

I just looked at the [POSIX shell specification](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html) (2.6.4 Arithmetic Expansion) and both the prefix and postfix operators are not required to be implemented by the shell.

This should be fixed by 03f3ac3297dc1474d5954e03de99e102026200de, along with another fix (91b11d3e30331b3dfc714111cf1b165279922bab) in the ioctl tool.
